-- Game extensions: a base game (e.g. Catan) can have extensions (Catan Marins,
-- Villes & Chevaliers…) that COMPOSE — several may be active on one played game.
-- An extension declares deltas on the base game's config template
-- (config_fields, merged by key) and/or its scoring (scoring_delta appends
-- categories). Some extensions are organised in scenarios (Marins), each with a
-- hard-coded win target and its own board (board_key, generated by the tool).

create table public.extensions (
  id            uuid primary key default gen_random_uuid(),
  base_game_id  uuid not null references public.boardgames (id) on delete cascade,
  name          text not null,
  -- FieldSpec[] merged onto the base config template (by key).
  config_fields jsonb not null default '[]',
  -- { appendSheet: ScoreSheetItem[] } appended to the base scoresheet, or null.
  scoring_delta jsonb,
  -- Additive modifier to the win target (never negative — an extension may raise
  -- the score to reach, never lower it). Scenario-based extensions set the base
  -- target on the scenario and keep this 0.
  target_modifier integer not null default 0,
  has_scenarios boolean not null default false,
  changes_board boolean not null default false,
  is_active     boolean not null default true,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

create table public.extension_scenarios (
  id           uuid primary key default gen_random_uuid(),
  extension_id uuid not null references public.extensions (id) on delete cascade,
  name         text not null,
  -- Hard-coded score to reach (read-only in the app); null if not applicable.
  target_score integer,
  -- Key the board generator reads to build this scenario's board.
  board_key    text,
  sort_order   integer not null default 0
);

-- Which extensions (and, for scenario-based ones, which scenario) a played game
-- used. Deleting the game cascades; extensions/scenarios can't be deleted while
-- referenced by a game (preserve history).
create table public.game_extensions (
  game_id      uuid not null references public.games (id) on delete cascade,
  extension_id uuid not null references public.extensions (id) on delete restrict,
  scenario_id  uuid references public.extension_scenarios (id) on delete restrict,
  primary key (game_id, extension_id)
);

-- Same access model as the rest: authenticated read; anon denied by RLS (no anon
-- policy) even though the grant is permissive. game_extensions is written when a
-- game is created / abandoned.
alter table public.extensions enable row level security;
alter table public.extension_scenarios enable row level security;
alter table public.game_extensions enable row level security;

create policy extensions_read on public.extensions
  for select to authenticated using (true);
create policy extension_scenarios_read on public.extension_scenarios
  for select to authenticated using (true);
create policy game_extensions_read on public.game_extensions
  for select to authenticated using (true);
create policy game_extensions_insert on public.game_extensions
  for insert to authenticated with check (true);
create policy game_extensions_delete on public.game_extensions
  for delete to authenticated using (true);

grant select on public.extensions to anon, authenticated;
grant select on public.extension_scenarios to anon, authenticated;
grant select, insert, delete on public.game_extensions to anon, authenticated;

-- Seed: Catan Marins + a first couple of scenarios (more added with their boards).
with ext as (
  insert into public.extensions
    (base_game_id, name, has_scenarios, changes_board, sort_order)
  values
    (
      '78047bc0-5293-4787-be48-ba7339d48c2d',
      'Catan - Marins',
      true,
      true,
      0
    )
  returning id
)
insert into public.extension_scenarios
  (extension_id, name, target_score, board_key, sort_order)
select ext.id, v.name, v.target, v.key, v.ord
from ext,
  (
    values
      ('À la découverte de nouveaux rivages', 14, 'heading-for-new-shores', 0),
      ('Les quatre îles', 13, 'four-islands', 1)
  ) as v (name, target, key, ord);
